COPY INTO SUB FROM @s3_stage/ FILES = ('sub.txt') FILE_FORMAT = TXT_FILE_FORMAT;
COPY INTO num FROM @s3_stage/ FILES = ('num.txt') FILE_FORMAT = TXT_FILE_FORMAT;
COPY INTO TAG FROM @s3_stage/ FILES = ('tag.txt') FILE_FORMAT = TXT_FILE_FORMAT;
COPY INTO pre FROM @s3_stage/ FILES = ('pre.txt') FILE_FORMAT = TXT_FILE_FORMAT;